[build]
  base = "unfollow-check/"
  command = "npm install --legacy-peer-deps --no-optional && npm run build"
  publish = "unfollow-check/dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --no-optional"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
