[build]
  base = "unfollow-check"
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10"
  VITE_GITHUB_TOKEN = "$VITE_GITHUB_TOKEN"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
